#!/usr/bin/env node
/**
 * generate-embedded-font-css — regenerate the render font asset
 * (deviation 12 resolution, after PR #194's render-regression failure).
 *
 * The print CSS used to say `font-family: serif`, which fontconfig resolved
 * to DejaVu Serif on the capture box and to a DIFFERENT face on
 * ubuntu-latest — every baseline drifted 1–4% in CI. Rendering is now
 * FONT-SELF-CONTAINED: the exact DejaVu Serif files (Book + Bold — the two
 * faces `serif`/`serif:bold` resolved to at capture time) are embedded into
 * the print HTML as base64 @font-face sources under the private family name
 * "MGS Render Serif", and the layout names ONLY that family, so no runner's
 * system fonts can leak into a render. Italic is synthesised by Chromium
 * from the regular face — deterministic, since the engine and the file are
 * both pinned.
 *
 *   node tools/generate-embedded-font-css [--fonts-dir <dir>]
 *
 * Writes libs/shared/assets/fonts/dejavu-embedded.css. Re-run only when
 * deliberately changing the render font; the pixel baselines pin the result,
 * so a font change is a baseline recapture (LER-1156's script) and a
 * reviewed diff, never an accident. DejaVu's licence (Bitstream Vera +
 * public-domain additions) permits redistribution; a copy ships beside the
 * generated asset.
 */
const { readFileSync, writeFileSync, mkdirSync, existsSync } = require('node:fs');
const { join, resolve } = require('node:path');

const argIdx = process.argv.indexOf('--fonts-dir');
const FONTS_DIR = argIdx >= 0 ? process.argv[argIdx + 1] : '/usr/share/fonts/truetype/dejavu';
const OUT_DIR = resolve(__dirname, '..', '..', 'libs', 'shared', 'assets', 'fonts');

const FACES = [
  { file: 'DejaVuSerif.ttf', weight: 400 },
  { file: 'DejaVuSerif-Bold.ttf', weight: 700 },
];

/** The family name the layout uses. Private on purpose: a name no system
 *  font registry will ever match, so a failed embed can only fall back to
 *  Chromium's last-resort face — which the pixel gate then catches. */
const FAMILY = 'MGS Render Serif';

mkdirSync(OUT_DIR, { recursive: true });
const rules = [];
for (const { file, weight } of FACES) {
  const path = join(FONTS_DIR, file);
  if (!existsSync(path)) {
    console.error(`missing font file: ${path}`);
    process.exit(1);
  }
  const data = readFileSync(path);
  rules.push(
    `/* ${file} · ${data.length} bytes · sha256 ${require('node:crypto').createHash('sha256').update(data).digest('hex').slice(0, 16)}… */\n` +
      `@font-face { font-family: '${FAMILY}'; font-weight: ${weight}; font-style: normal;` +
      ` src: url(data:font/ttf;base64,${data.toString('base64')}) format('truetype'); }`,
  );
  console.log(`${file}: ${data.length} bytes embedded (weight ${weight})`);
}
const banner =
  `/* GENERATED by tools/generate-embedded-font-css — do not edit by hand.\n` +
  ` * Family "${FAMILY}" = DejaVu Serif Book/Bold, embedded so every render\n` +
  ` * resolves every glyph from these bytes on any machine (deviation 12).\n` +
  ` * Licence: see LICENSE-DejaVu.txt beside this file. */\n`;
writeFileSync(join(OUT_DIR, 'dejavu-embedded.css'), banner + rules.join('\n') + '\n');
console.log(`wrote ${join(OUT_DIR, 'dejavu-embedded.css')}`);
