/**
 * UC-09: layout as data behind an interface (PRD §4).
 *
 * A FormLayout declares page geometry and typography as DATA, versioned like
 * templates; a LayoutBinding maps (template, layout, values) → RenderModel.
 * The one shipped implementation is CleanA4Binding — a clean A4 rendering
 * that claims structure, never facsimile (no official HMCTS source exists to
 * copy: docs/answers/template-sourcing-evidence-2026-08.md). If an official
 * specimen ever materialises, an overlay-coordinate binding is a SECOND
 * implementation of this interface, not a rewrite of the renderer.
 */

import { FormTemplate } from './form-template.types';
import {
  BuildRenderModelOptions,
  buildRenderModel,
  RenderModel,
} from './render-model';

export interface FormLayout {
  id: string;
  /** Bump on any geometry/typography change — reference baselines pin it. */
  version: number;
  page: {
    size: 'A4';
    /** Top margin is larger: the running draft band lives in it. */
    marginMm: { top: number; right: number; bottom: number; left: number };
  };
  /** Point sizes, not device pixels — this is print. */
  type: {
    bodyPt: number;
    labelPt: number;
    headingPt: number;
    /** The embedded family and nothing else — glyphs must resolve from the
     *  bytes the render ships, never from whatever the machine has. */
    family: string;
  };
}

/** The shipped layout. One for all eleven forms on purpose — a per-form
 *  geometry would be a facsimile claim the sourcing evidence cannot back. */
export const CLEAN_A4_LAYOUT: FormLayout = {
  id: 'clean-a4',
  // v2: the render font became SELF-CONTAINED (deviation 12 — PR #194's
  // render-regression failed on ubuntu-latest because `serif` resolved to a
  // different face there). The family below exists only as the embedded
  // @font-face (libs/shared/assets/fonts, generated by
  // tools/generate-embedded-font-css); no generic fallback ON PURPOSE, so a
  // runner's system fonts can never leak into a render.
  version: 2,
  page: {
    size: 'A4',
    marginMm: { top: 22, right: 14, bottom: 18, left: 14 },
  },
  type: {
    bodyPt: 10,
    labelPt: 7.5,
    headingPt: 12,
    family: "'MGS Render Serif'",
  },
};

export interface LayoutBinding {
  readonly layout: FormLayout;
  bind(
    template: FormTemplate,
    values: Record<string, unknown>,
    opts: BuildRenderModelOptions,
  ): RenderModel;
}

export class CleanA4Binding implements LayoutBinding {
  readonly layout = CLEAN_A4_LAYOUT;

  bind(
    template: FormTemplate,
    values: Record<string, unknown>,
    opts: BuildRenderModelOptions,
  ): RenderModel {
    return buildRenderModel(template, values, opts);
  }
}
